-- InnaOpcja.pl — seed: 26 telefonów (15 zapytań + 11 alternatyw), wszystkie dane
-- zweryfikowane realnym researchem (specs, ceny PLN, istnienie modelu) we wrześniu 2026.

INSERT INTO products (category_id, name, slug, normalized_name, brand, brand_recognition, verdict, score, summary, pros, cons, specs, price_tier, status) VALUES

((SELECT id FROM categories WHERE slug = 'telefony'), 'iPhone 17', 'iphone-17', 'iphone 17', 'Apple', 'mainstream',
 'Solidny wybór, ale nie najlepszy stosunek ceny do możliwości w tej cenie', 8.0,
 'Podstawowy iPhone 17 oferuje topowy chipset Apple A19 i dopracowany ekosystem, ale przy 8 GB RAM i pojedynczym aparacie 48 MP nie jest liderem specyfikacji w swojej cenie.',
 '["Najnowszy chipset Apple A19", "Długie wsparcie systemowe (iOS)", "Kompaktowy, poręczny rozmiar ekranu 6,3\""]'::jsonb,
 '["Tylko 8 GB RAM przy tej cenie", "Pojedynczy aparat główny, brak teleobiektywu", "Bateria mniejsza niż u konkurencji Android"]'::jsonb,
 '{"screen_size_inches": 6.3, "chipset": "Apple A19", "chipset_tier": 5, "ram_gb": 8, "camera_main_mp": 48, "battery_mah": 3692, "price_pln_approx": "3700-3930"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Samsung Galaxy S26', 'samsung-galaxy-s26', 'samsung galaxy s26', 'Samsung', 'mainstream',
 'Bardzo dobry flagowiec bazowy — mocny chipset w rozsądnej cenie jak na segment', 8.2,
 'Bazowy model serii S26 z topowym Snapdragonem 8 Elite Gen 5 i dużym ekranem AMOLED, przy relatywnie niższej barierze wejścia niż konkurencja.',
 '["Topowy chipset Snapdragon 8 Elite Gen 5", "Ekran AMOLED 120Hz", "Dobra relacja cena/wydajność jak na flagowca"]'::jsonb,
 '["Pojedynczy aparat główny 50MP, bez teleobiektywu", "Mniejsza bateria (4300 mAh) niż u rywali"]'::jsonb,
 '{"screen_size_inches": 6.3, "chipset": "Snapdragon 8 Elite Gen 5 for Galaxy", "chipset_tier": 5, "ram_gb": 12, "camera_main_mp": 50, "battery_mah": 4300, "price_pln_approx": "3039-4499"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Samsung Galaxy S26 Ultra', 'samsung-galaxy-s26-ultra', 'samsung galaxy s26 ultra', 'Samsung', 'mainstream',
 'Najlepszy aparat w ofercie Samsunga, ale cena zbliża się do granicy opłacalności', 7.8,
 'Poczwórny aparat 200MP z peryskopem i rysik S Pen czynią z S26 Ultra najbardziej rozbudowany telefon Samsunga, kosztem bardzo wysokiej ceny.',
 '["Poczwórny aparat z teleobiektywem peryskopowym 200MP", "Rysik S Pen w zestawie", "Ekran QHD+ najwyższej jakości"]'::jsonb,
 '["Bardzo wysoka cena (6499 zł)", "Duży i ciężki telefon"]'::jsonb,
 '{"screen_size_inches": 6.9, "chipset": "Snapdragon 8 Elite Gen 5 for Galaxy", "chipset_tier": 5, "ram_gb": 12, "camera_main_mp": 200, "battery_mah": 4855, "price_pln_approx": "6499"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'iPhone 17 Pro', 'iphone-17-pro', 'iphone 17 pro', 'Apple', 'mainstream',
 'Solidny skok względem podstawowego iPhone''a, ale drogi jak na przyrost możliwości', 7.5,
 'Potrójny aparat i 12 GB RAM to realne ulepszenia względem iPhone''a 17, jednak różnica cenowa jest spora.',
 '["Potrójny aparat 48+12+48MP", "12 GB RAM", "Chipset A19 Pro z lepszym chłodzeniem"]'::jsonb,
 '["Znaczna dopłata względem iPhone 17", "Bateria wciąż poniżej 4000 mAh"]'::jsonb,
 '{"screen_size_inches": 6.3, "chipset": "Apple A19 Pro", "chipset_tier": 5, "ram_gb": 12, "camera_main_mp": 48, "battery_mah": 3988, "price_pln_approx": "5349-5800"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'realme 16 Pro+', 'realme-16-pro-plus', 'realme 16 pro plus', 'realme', 'niche',
 'Bardzo dobra propozycja w segmencie średnim — ogromna bateria i mocny aparat 200MP', 8.3,
 'realme 16 Pro+ łączy 200-megapikselowy aparat, 7000 mAh baterii i wysokie odświeżanie ekranu w cenie znacznie niższej niż flagowce.',
 '["Aparat główny 200MP", "Bateria 7000 mAh", "Ekran 144Hz"]'::jsonb,
 '["Mniej rozpoznawalna marka w Polsce", "Chipset średniej klasy (Snapdragon 7 Gen 4), nie flagowy"]'::jsonb,
 '{"screen_size_inches": 6.78, "chipset": "Snapdragon 7 Gen 4", "chipset_tier": 3, "ram_gb": 8, "camera_main_mp": 200, "battery_mah": 7000, "price_pln_approx": "2499"}'::jsonb,
 'sredni', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Samsung Galaxy A57 5G', 'samsung-galaxy-a57-5g', 'samsung galaxy a57 5g', 'Samsung', 'mainstream',
 'Solidny, ale przeciętny średniak — bez wyróżników poza marką', 7.3,
 'Galaxy A57 5G oferuje sprawdzoną formułę Samsunga w segmencie A, ale ustępuje konkurencji w kluczowych podzespołach za podobne pieniądze.',
 '["Ekran Super AMOLED 120Hz", "Marka Samsung i długie wsparcie"]'::jsonb,
 '["Chipset Exynos 1680 słabszy niż konkurencja w tej cenie", "Pojedynczy aparat główny bez wyróżniających się parametrów"]'::jsonb,
 '{"screen_size_inches": 6.7, "chipset": "Exynos 1680", "chipset_tier": 2, "ram_gb": 8, "camera_main_mp": 50, "battery_mah": 5000, "price_pln_approx": "2309-2569"}'::jsonb,
 'sredni', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Samsung Galaxy A16', 'samsung-galaxy-a16', 'samsung galaxy a16', 'Samsung', 'mainstream',
 'Bardzo budżetowy wybór — ograniczony przez 4 GB RAM', 6.8,
 'Najtańszy telefon Samsunga w zestawieniu, z ekranem AMOLED, ale słabym chipsetem i tylko 4 GB RAM.',
 '["Bardzo niska cena", "Ekran Super AMOLED (rzadkość w tym segmencie)", "6 lat aktualizacji od Samsunga"]'::jsonb,
 '["Tylko 4 GB RAM", "Słaby chipset Exynos 1330", "Odświeżanie ekranu ograniczone do 90Hz"]'::jsonb,
 '{"screen_size_inches": 6.7, "chipset": "Exynos 1330", "chipset_tier": 1, "ram_gb": 4, "camera_main_mp": 50, "battery_mah": 5000, "price_pln_approx": "799-999"}'::jsonb,
 'budzetowy', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Xiaomi 17T Pro', 'xiaomi-17t-pro', 'xiaomi 17t pro', 'Xiaomi', 'mainstream',
 'Sub-flagowiec z bardzo mocnym chipsetem za rozsądną cenę', 8.0,
 'Dimensity 9500 to jeden z najmocniejszych chipsetów na rynku, a Xiaomi oferuje go poniżej ceny typowych flagowców.',
 '["Chipset MediaTek Dimensity 9500 (top wydajność)", "Bateria 7000 mAh", "Ekran 144Hz 1.5K"]'::jsonb,
 '["Brak pełnej gamy aparatów flagowca (brak teleobiektywu)", "Pozycjonowany poniżej głównej serii Xiaomi 17"]'::jsonb,
 '{"screen_size_inches": 6.83, "chipset": "MediaTek Dimensity 9500", "chipset_tier": 4, "ram_gb": 12, "camera_main_mp": 50, "battery_mah": 7000, "price_pln_approx": "3699"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Google Pixel 10 Pro', 'google-pixel-10-pro', 'google pixel 10 pro', 'Google', 'niche',
 'Najlepszy aparat obliczeniowy na rynku, ale niszowy w Polsce', 7.9,
 'Potrójny aparat 50+48+48MP i czysty Android z najlepszym wsparciem AI, kosztem mniejszej rozpoznawalności marki w Polsce.',
 '["Doskonały aparat obliczeniowy Google", "16 GB RAM", "Czysty Android, szybkie aktualizacje"]'::jsonb,
 '["Mała sieć serwisowa w Polsce", "Tensor G5 ustępuje w benchmarkach Snapdragonowi 8 Elite"]'::jsonb,
 '{"screen_size_inches": 6.3, "chipset": "Google Tensor G5", "chipset_tier": 5, "ram_gb": 16, "camera_main_mp": 50, "battery_mah": 4870, "price_pln_approx": "4849"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'iPhone 17 Pro Max', 'iphone-17-pro-max', 'iphone 17 pro max', 'Apple', 'mainstream',
 'Najlepszy iPhone w ofercie, ale przy tej cenie warto rozważyć alternatywy', 7.3,
 'Największy ekran, najdłużej działająca bateria i potrójny aparat w najdroższym iPhonie z bieżącej serii.',
 '["Największa bateria wśród iPhone''ów (do 5088 mAh)", "Ekran 6,9\"", "Potrójny aparat 48MP"]'::jsonb,
 '["Najwyższa cena w zestawieniu obok Ultra i X300 Ultra", "Duży i ciężki telefon"]'::jsonb,
 '{"screen_size_inches": 6.9, "chipset": "Apple A19 Pro", "chipset_tier": 5, "ram_gb": 12, "camera_main_mp": 48, "battery_mah": 4823, "price_pln_approx": "5475-5648"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Samsung Galaxy S25 Ultra', 'samsung-galaxy-s25-ultra', 'samsung galaxy s25 ultra', 'Samsung', 'mainstream',
 'Świetna okazja — flagowiec sprzed roku, mocno przeceniony po premierze S26', 8.4,
 'Po debiucie Galaxy S26 ceny S25 Ultra spadły, a wciąż oferuje on poczwórny aparat 200MP i rysik S Pen — bardzo dobra wartość.',
 '["Poczwórny aparat 200MP z rysikiem S Pen", "Znacząca obniżka ceny po premierze następcy", "Bateria 5000 mAh"]'::jsonb,
 '["Starszy chipset niż S26", "Krótsze wsparcie aktualizacji niż nowszy model"]'::jsonb,
 '{"screen_size_inches": 6.9, "chipset": "Snapdragon 8 Elite for Galaxy", "chipset_tier": 5, "ram_gb": 12, "camera_main_mp": 200, "battery_mah": 5000, "price_pln_approx": "3499-4199"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'POCO X8 Pro', 'poco-x8-pro', 'poco x8 pro', 'POCO', 'niche',
 'Bardzo dobry stosunek wydajności do ceny w segmencie średnim', 8.3,
 'POCO X8 Pro oferuje mocny chipset Dimensity 8500-Ultra i dużą baterię w bardzo konkurencyjnej cenie.',
 '["Mocny chipset jak na segment średni", "Bateria 6500 mAh", "Bardzo dobra cena"]'::jsonb,
 '["Marka mniej znana niż Samsung/Xiaomi", "Pojedynczy aparat główny bez teleobiektywu"]'::jsonb,
 '{"screen_size_inches": 6.59, "chipset": "MediaTek Dimensity 8500-Ultra", "chipset_tier": 3, "ram_gb": 8, "camera_main_mp": 50, "battery_mah": 6500, "price_pln_approx": "1499-1899"}'::jsonb,
 'sredni', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Motorola Moto G86 Power', 'motorola-moto-g86-power', 'motorola moto g86 power', 'Motorola', 'niche',
 'Rekordowa bateria w rozsądnej cenie budżetowej', 8.0,
 'Moto G86 Power wyróżnia się baterią 6720 mAh i ekranem AMOLED w cenie budżetowego smartfona.',
 '["Bateria 6720 mAh", "12 GB RAM jak na budżetowy segment", "Aparat z OIS"]'::jsonb,
 '["Chipset średniej klasy (Dimensity 7300)", "Mniej rozpoznawalna marka w Polsce niż Samsung/Xiaomi"]'::jsonb,
 '{"screen_size_inches": 6.67, "chipset": "MediaTek Dimensity 7300", "chipset_tier": 2, "ram_gb": 12, "camera_main_mp": 50, "battery_mah": 6720, "price_pln_approx": "1399"}'::jsonb,
 'budzetowy', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'iPhone 15', 'iphone-15', 'iphone 15', 'Apple', 'mainstream',
 'Wciąż bardzo dobry iPhone, choć cena nie spadła tak mocno jak można by oczekiwać', 7.8,
 'Starszy, ale wciąż wydajny iPhone z chipsetem A16 Bionic — dobra opcja dla wchodzących w ekosystem Apple, choć cena trzyma się mocno.',
 '["Sprawdzony chipset A16 Bionic", "Kompaktowy rozmiar 6,1\"", "Ekosystem Apple"]'::jsonb,
 '["Tylko 6 GB RAM", "Cena spadła mniej niż w przypadku konkurencji Android", "Pojedynczy aparat główny"]'::jsonb,
 '{"screen_size_inches": 6.1, "chipset": "Apple A16 Bionic", "chipset_tier": 4, "ram_gb": 6, "camera_main_mp": 48, "battery_mah": 3349, "price_pln_approx": "2389-2600"}'::jsonb,
 'sredni', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Samsung Galaxy A56 5G', 'samsung-galaxy-a56-5g', 'samsung galaxy a56 5g', 'Samsung', 'mainstream',
 'Solidny średniak Samsunga z dobrym ekranem', 7.6,
 'Galaxy A56 5G to sprawdzona formuła: ekran Super AMOLED 120Hz i wystarczająca wydajność do codziennych zadań.',
 '["Ekran Super AMOLED 120Hz", "Marka Samsung, długie wsparcie", "Potrójny aparat"]'::jsonb,
 '["Chipset Exynos 1580 ustępuje konkurencji Android w tej cenie", "Ładowanie wolniejsze niż u konkurencji"]'::jsonb,
 '{"screen_size_inches": 6.7, "chipset": "Exynos 1580", "chipset_tier": 3, "ram_gb": 8, "camera_main_mp": 50, "battery_mah": 5000, "price_pln_approx": "1499-1799"}'::jsonb,
 'sredni', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'vivo X300 Ultra', 'vivo-x300-ultra', 'vivo x300 ultra', 'vivo', 'niche',
 'Szczyt możliwości fotograficznych, ale ekstremalna cena ogranicza wartość', 6.5,
 'Poczwórny aparat 200MP z podwójnym teleobiektywem to popis technologii, jednak przy cenie 8499 zł to propozycja tylko dla entuzjastów fotografii mobilnej.',
 '["Poczwórny aparat 200MP z podwójnym teleobiektywem", "Bateria 6600 mAh", "Współpraca z ZEISS"]'::jsonb,
 '["Najwyższa cena w całym zestawieniu", "Marka słabo znana w Polsce, ograniczony serwis"]'::jsonb,
 '{"screen_size_inches": 6.82, "chipset": "Snapdragon 8 Elite Gen 5", "chipset_tier": 5, "ram_gb": 12, "camera_main_mp": 200, "battery_mah": 6600, "price_pln_approx": "8499"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Google Pixel 10', 'google-pixel-10', 'google pixel 10', 'Google', 'niche',
 'Bardzo dobry flagowiec do zdjęć w cenie niższej niż konkurencja', 8.1,
 'Podstawowy Pixel 10 oferuje potrójny aparat i czysty Android w cenie wyraźnie niższej niż odpowiedniki Apple i Samsunga.',
 '["Potrójny aparat z dobrym peryskopem", "Czysty Android, szybkie aktualizacje", "Niższa cena niż iPhone 17 czy Galaxy S26"]'::jsonb,
 '["Mniejsza rozpoznawalność marki w Polsce", "Tensor G5 słabszy w testach wydajności niż konkurencja"]'::jsonb,
 '{"screen_size_inches": 6.3, "chipset": "Google Tensor G5", "chipset_tier": 5, "ram_gb": 12, "camera_main_mp": 48, "battery_mah": 4970, "price_pln_approx": "3949"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'OnePlus 15R', 'oneplus-15r', 'oneplus 15r', 'OnePlus', 'niche',
 'Flagowy chipset w cenie segmentu średniego — bardzo dobra oferta', 8.2,
 'OnePlus 15R przenosi Snapdragona 8 Gen 5 do niższej półki cenowej, dokładając ogromną baterię 7400 mAh.',
 '["Flagowy chipset Snapdragon 8 Gen 5", "Bateria 7400 mAh — jedna z największych w zestawieniu", "Bardzo dobra cena jak na wydajność"]'::jsonb,
 '["Marka mniej znana niż Samsung czy Apple", "Aparat bez teleobiektywu"]'::jsonb,
 '{"screen_size_inches": 6.78, "chipset": "Snapdragon 8 Gen 5", "chipset_tier": 4, "ram_gb": 12, "camera_main_mp": 50, "battery_mah": 7400, "price_pln_approx": "2799-3000"}'::jsonb,
 'sredni', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'HONOR Magic8 Pro', 'honor-magic8-pro', 'honor magic8 pro', 'HONOR', 'niche',
 'Mocny flagowiec fotograficzny, ale drogi i mało znany w Polsce', 7.0,
 'Potrójny aparat z teleobiektywem 200MP i topowy chipset stawiają Magic8 Pro w lidze najlepszych, jednak cena i rozpoznawalność marki to bariery.',
 '["Potrójny aparat z teleobiektywem 200MP", "Topowy chipset Snapdragon 8 Elite Gen 5", "16 GB RAM"]'::jsonb,
 '["Wysoka cena", "Marka mało znana w Polsce, ograniczony serwis"]'::jsonb,
 '{"screen_size_inches": 6.71, "chipset": "Snapdragon 8 Elite Gen 5", "chipset_tier": 5, "ram_gb": 16, "camera_main_mp": 50, "battery_mah": 6270, "price_pln_approx": "5799"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Redmi Note 15 Pro+', 'redmi-note-15-pro-plus', 'redmi note 15 pro plus', 'Redmi', 'niche',
 'Bardzo dobry aparat 200MP w przystępnej cenie segmentu średniego', 8.2,
 'Redmi Note 15 Pro+ oferuje aparat 200MP i dużą baterię w cenie, która wyraźnie podbija konkurencję w segmencie średnim.',
 '["Aparat główny 200MP", "Bateria 6500 mAh (wersja PL)", "Bardzo dobra cena"]'::jsonb,
 '["Chipset średniej klasy (Snapdragon 7s Gen 4)", "Marka postrzegana jako budżetowa"]'::jsonb,
 '{"screen_size_inches": 6.83, "chipset": "Snapdragon 7s Gen 4", "chipset_tier": 2, "ram_gb": 8, "camera_main_mp": 200, "battery_mah": 6500, "price_pln_approx": "1999-2299"}'::jsonb,
 'sredni', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'OnePlus 15', 'oneplus-15', 'oneplus 15', 'OnePlus', 'niche',
 'Flagowiec, który realnie kosztuje mniej niż poprzednik — bardzo dobra wartość', 8.4,
 'OnePlus 15 łączy topowy Snapdragon 8 Elite Gen 5, ekran 165Hz i baterię 7300 mAh w cenie niższej niż wcześniejsza generacja.',
 '["Topowy chipset Snapdragon 8 Elite Gen 5", "Ekran 165Hz", "Bateria 7300 mAh"]'::jsonb,
 '["Marka mniej rozpoznawalna niż Samsung/Apple", "Ograniczona dostępność serwisu w Polsce"]'::jsonb,
 '{"screen_size_inches": 6.78, "chipset": "Snapdragon 8 Elite Gen 5", "chipset_tier": 5, "ram_gb": 12, "camera_main_mp": 50, "battery_mah": 7300, "price_pln_approx": "3999"}'::jsonb,
 'premium', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Nothing Phone (4a) Pro', 'nothing-phone-4a-pro', 'nothing phone 4a pro', 'Nothing', 'niche',
 'Ciekawy design i dobry aparat z peryskopem w segmencie średnim', 7.7,
 'Nothing Phone (4a) Pro wyróżnia się unikalnym designem i aparatem z peryskopem 3,5x, będąc obecnie najwyżej pozycjonowanym modelem marki.',
 '["Unikalny design", "Aparat z peryskopem (zoom 3,5x)", "Dobra cena jak na możliwości"]'::jsonb,
 '["Chipset średniej klasy (Snapdragon 7 Gen 4)", "Marka niszowa, brak flagowca w ofercie w 2026"]'::jsonb,
 '{"screen_size_inches": 6.83, "chipset": "Snapdragon 7 Gen 4", "chipset_tier": 2, "ram_gb": 8, "camera_main_mp": 50, "battery_mah": 5080, "price_pln_approx": "2099"}'::jsonb,
 'sredni', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'TCL 60R 5G', 'tcl-60r-5g', 'tcl 60r 5g', 'TCL', 'niche',
 'Najtańsza opcja z 5G w zestawieniu — solidna baza za bardzo małe pieniądze', 7.0,
 'TCL 60R 5G to budżetowy telefon z 5G, dużą baterią 5200 mAh i ekranem 120Hz za mniej niż 500 zł.',
 '["Bardzo niska cena (ok. 500 zł)", "Bateria 5200 mAh", "Obsługa 5G mimo niskiej ceny"]'::jsonb,
 '["Tylko 4 GB RAM", "Ekran HD+ (niska rozdzielczość)", "Marka mało znana w Polsce"]'::jsonb,
 '{"screen_size_inches": 6.67, "chipset": "MediaTek Dimensity 6300", "chipset_tier": 1, "ram_gb": 4, "camera_main_mp": 50, "battery_mah": 5200, "price_pln_approx": "495-504"}'::jsonb,
 'budzetowy', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'CMF Phone', 'cmf-phone', 'cmf phone', 'CMF', 'niche',
 'Solidna budżetowa baza od sub-marki Nothing, choć to już starszy model', 6.9,
 'CMF Phone (2024) oferuje przyzwoite parametry w bardzo niskiej cenie, choć od premiery zdążył się doczekać nowszego następcy.',
 '["Bardzo niska cena", "8 GB RAM jak na budżetowy segment", "Charakterystyczny design"]'::jsonb,
 '["Aparat główny bez OIS", "To już starszy model (2024), następca CMF Phone 2 Pro jest nowszy"]'::jsonb,
 '{"screen_size_inches": 6.67, "chipset": "MediaTek Dimensity 7300", "chipset_tier": 2, "ram_gb": 8, "camera_main_mp": 50, "battery_mah": 5000, "price_pln_approx": "869"}'::jsonb,
 'budzetowy', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'Motorola Moto G86', 'motorola-moto-g86', 'motorola moto g86', 'Motorola', 'niche',
 'Bardzo dobra baza budżetowa — solidny aparat i bateria za niewielkie pieniądze', 7.6,
 'Moto G86 to tańszy wariant G86 Power, wciąż oferujący dobry aparat 50MP i baterię 5200 mAh.',
 '["Bardzo dobra cena", "Aparat 50MP z dodatkowym ultraszerokim", "Bateria 5200 mAh"]'::jsonb,
 '["Chipset średniej klasy (Dimensity 7300)", "Mniej RAM niż w wariancie Power"]'::jsonb,
 '{"screen_size_inches": 6.67, "chipset": "MediaTek Dimensity 7300", "chipset_tier": 2, "ram_gb": 8, "camera_main_mp": 50, "battery_mah": 5200, "price_pln_approx": "899-1200"}'::jsonb,
 'budzetowy', 'published'),

((SELECT id FROM categories WHERE slug = 'telefony'), 'vivo X300 Pro', 'vivo-x300-pro', 'vivo x300 pro', 'vivo', 'niche',
 'Aparat klasy flagowej z teleobiektywem ZEISS, ale marka wciąż niszowa w Polsce', 7.0,
 'vivo X300 Pro oferuje aparat 200MP z teleobiektywem ZEISS APO na poziomie najlepszych flagowców, w cenie poniżej topowego wariantu Ultra.',
 '["Aparat 200MP z teleobiektywem ZEISS APO", "Chipset Dimensity 9500", "Bateria 6510 mAh"]'::jsonb,
 '["Wysoka cena mimo braku pozycji \"Ultra\"", "Marka mało znana w Polsce, ograniczony serwis"]'::jsonb,
 '{"screen_size_inches": 6.78, "chipset": "MediaTek Dimensity 9500", "chipset_tier": 4, "ram_gb": 12, "camera_main_mp": 200, "battery_mah": 6510, "price_pln_approx": "5999"}'::jsonb,
 'premium', 'published');
